# Generated by Django 2.1.1 on 2019-03-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_link_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
