# Generated by Django 2.1.1 on 2019-03-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190307_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
